apr:
  conda-forge:
    - apr
asio:
  conda-forge:
    - asio
assimp:
  conda-forge:
    - assimp
boost:
  conda-forge:
    - "boost 1.72.*"
bullet:
  conda-forge:
    - bullet
bzip2:
  conda-forge:
    - bzip2
cmake:
  conda-forge:
    - cmake
colcon-common-extensions:
  conda-forge:
    - colcon-common-extensions
cppcheck:
  conda-forge:
    - cppcheck
curl:
  conda-forge:
    - libcurl
eigen:
  conda-forge:
    - eigen
fastcdr:
  conda-forge:
    - fast-cdr
fastrtps:
  conda-forge:
    - fast-rtps
git:
  conda-forge:
    - git
google-mock:
  conda-forge:
    - gmock
graphicsmagick:
  conda-forge:
    - graphicsmagick
graphviz:
  conda-forge:
    - graphviz
gtest:
  conda-forge:
    - gtest
lcov:
  conda-forge:
    - lcov
libboost-chrono-dev:
  conda-forge:
    - "boost 1.72.*"
libboost-date-time-dev:
  conda-forge:
    - "boost 1.72.*"
libboost-filesystem-dev:
  conda-forge:
    - "boost 1.72.*"
libboost-program-options:
  conda-forge:
    - "boost 1.72.*"
libboost-program-options-dev:
  conda-forge:
    - "boost 1.72.*"
libboost-regex-dev:
  conda-forge:
    - "boost 1.72.*"
libboost-system-dev:
  conda-forge:
    - "boost 1.72.*"
libboost-thread-dev:
  conda-forge:
    - "boost 1.72.*"
libconsole-bridge-dev:
  conda-forge:
    - console_bridge
libcunit-dev:
  conda-forge: []
libfreetype6:
  conda-forge:
    - freetype
libfreetype6-dev:
  conda-forge:
    - freetype
libgpgme-dev:
  conda-forge: []
libopencv-dev:
  conda-forge:
    - opencv 3*
liborocos-kdl:
  conda-forge:
    - orocos-kdl
liborocos-kdl-dev:
  conda-forge:
    - orocos-kdl
libpcl-all-dev:
  conda-forge:
    - pcl
libpoco-dev:
  conda-forge:
    - poco
libqt5-core:
  conda-forge:
    - qt
libqt5-gui:
  conda-forge:
    - qt
libqt5-opengl:
  conda-forge:
    - qt
libqt5-widgets:
  conda-forge:
    - qt
libssl-dev:
  conda-forge:
    - openssl
liburdfdom-dev:
  conda-forge:
    - urdfdom
liburdfdom-headers-dev:
  conda-forge:
    - urdfdom_headers
libx11-dev:
  conda-forge: []
libxaw:
  conda-forge: []
libxml2-utils:
  conda-forge:
    - libxml2
libxrandr:
  conda-forge: []
libzmq3-dev:
  conda-forge:
    - zeromq
log4cxx:
  conda-forge:
    - log4cxx
lz4:
  conda-forge:
    - lz4
opengl:
  conda-forge: []
openssl:
  conda-forge:
    - openssl
pcre:
  conda-forge:
    - pcre
pkg-config:
  conda-forge:
    - pkg-config
pydocstyle:
  conda-forge:
    - pydocstyle
python:
  conda-forge:
    - 'python {{ python }}'
python-argparse:
  conda-forge: []
python-catkin-pkg:
  conda-forge:
    - catkin_pkg
python-catkin-pkg-modules:
  conda-forge:
    - catkin_pkg
python-coverage:
  conda-forge:
    - coverage
python-crypto:
  conda-forge:
    - pycrypto
python-defusedxml:
  conda-forge:
    - defusedxml
python-empy:
  conda-forge:
    - empy
python-gnupg:
  conda-forge:
    - python-gnupg
python-imaging:
  conda-forge:
    - pillow
python-mock:
  conda-forge:
    - mock
python-netifaces:
  conda-forge:
    - netifaces
python-nose:
  conda-forge:
    - nose
python-numpy:
  conda-forge:
    - numpy
python-paramiko:
  conda-forge:
    - paramiko
python-pycryptodome:
  conda-forge:
    - pycryptodome
python-rosdep:
  conda-forge:
    - rosdep
python-rosdep-modules:
  conda-forge:
    - rosdep
python-rospkg:
  conda-forge:
    - rospkg
python-setuptools:
  conda-forge:
    - setuptools
python-yaml:
  conda-forge:
    - pyyaml
python3:
  conda-forge:
    - 'python {{ python }}'
python3-cairo:
  conda-forge:
    - pycairo
python3-catkin-pkg:
  conda-forge:
    - catkin_pkg
python3-catkin-pkg-modules:
  conda-forge:
    - catkin_pkg
python3-coverage:
  conda-forge:
    - coverage
python3-cryptography:
  conda-forge:
    - cryptography
python3-defusedxml:
  conda-forge:
    - defusedxml
python3-dev:
  conda-forge:
    - 'python {{ python }}'
python3-empy:
  conda-forge:
    - empy
python3-flake8:
  conda-forge:
    - flake8
python3-gnupg:
  conda-forge:
    - python-gnupg
python3-ifcfg:
  conda-forge:
    - ifcfg
python3-lark-parser:
  conda-forge:
    - lark-parser
python3-lxml:
  conda-forge:
    - lxml
python3-matplotlib:
  conda-forge:
    - matplotlib
python3-mock:
  conda-forge:
    - mock
python3-mypy:
  conda-forge:
    - mypy
python3-netifaces:
  conda-forge:
    - netifaces
python3-nose:
  conda-forge:
    - nose
python3-numpy:
  conda-forge:
    - numpy
python3-opencv:
  conda-forge:
    - py-opencv 3*
python3-paramiko:
  conda-forge:
    - paramiko
python3-pil:
  conda-forge:
    - pillow
python3-pkg-resources:
  conda-forge: []
python3-psutil:
  conda-forge:
    - psutil
python3-pycryptodome:
  conda-forge:
    - pycryptodome
python3-pydot:
  conda-forge:
    - pydot
python3-pygraphviz:
  conda-forge: []
python3-pykdl:
  conda-forge:
    - python-orocos-kdl
python3-pytest:
  conda-forge:
    - pytest
python3-pytest-mock:
  conda-forge:
    - pytest-mock
python3-qt5-bindings:
  conda-forge:
    - pyqt
python3-qt5-bindings-webkit:
  conda-forge: []
python3-rosdep:
  conda-forge:
    - rosdep
python3-rosdep-modules:
  conda-forge:
    - rosdep
python3-rosdistro-modules:
  conda-forge:
    - rosdistro
python3-rospkg:
  conda-forge:
    - rospkg
python3-setuptools:
  conda-forge:
    - setuptools
python3-yaml:
  conda-forge:
    - pyyaml
qt5-qmake:
  conda-forge:
    - qt
qtbase5-dev:
  conda-forge:
    - qt
sbcl:
  conda-forge: []
sdl:
  conda-forge:
    - sdl
sdl-image:
  conda-forge:
    - sdl_image
setuptools:
  conda-forge:
    - setuptools
spdlog:
  conda-forge:
    - spdlog
tango-icon-theme:
  conda-forge: []
tinyxml:
  conda-forge:
    - tinyxml
tinyxml2:
  conda-forge:
    - tinyxml2
uncrustify:
  conda-forge:
    - uncrustify
uuid:
  conda-forge: []
yaml:
  conda-forge:
    - yaml
yaml-cpp:
  conda-forge:
    - yaml-cpp
zlib:
  conda-forge:
    - zlib
